### ISSUE TITLE
Exception `No variant matched..` (RUntimeError) on specific file

### ISSUE THREAD

**Issue by kerrizor** [penelopezone/rubyfmt#181]
* Ruby version: 2.6.5
* Rubyfmt git sha: 43bcac1

## Input file
Running against https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/diff/inline_diff_markdown_marker.rb (7e6f6e1603d6905be1a7e1b49399b8c778196fc9)

```ruby
# frozen_string_literal: true

module Gitlab
  module Diff
    class InlineDiffMarkdownMarker < Gitlab::StringRangeMarker
      MARKDOWN_SYMBOLS = {
        addition: "+",
        deletion: "-"
      }.freeze

      def mark(line_inline_diffs, mode: nil)
        super(line_inline_diffs) do |text, left:, right:|
          symbol = MARKDOWN_SYMBOLS[mode]
          "{#{symbol}#{text}#{symbol}}"
        end
      end
    end
  end
end
```

## Rubyfmt's output

```
Traceback (most recent call last):
	1: from ../../../rubyfmt/rubyfmt.rb:237:in `<main>'
../../../rubyfmt/rubyfmt.rb:237:in `format_to_stdout': No variant matched untagged enum Expression. (Error from ripper_deserialize) (RuntimeError)
```

## This breaks because

Well, it shouldn't raise an exception here..

**Comment by penelopezone** [comment]
this reduces to:

```ruby
super do
end
```
